import React, { createContext, useContext, useState, useEffect } from "react";

const dict = {
  en: {
    // top strip
    "top.freeShip": "Free shipping across India on orders above ₹499",
    "top.offered": "Devotedly offered at Shri Mahakaleshwar Jyotirlinga",
    "top.disclaimer": "This service is not affiliated with the temple management",
    // nav
    "nav.home": "Home",
    "nav.shop": "Shop",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.faqs": "FAQs",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.myOrders": "My Orders",
    "nav.wishlist": "Wishlist",
    "nav.searchPh": "Search prasad, puja kits…",
    "nav.tagline": "Sacred from Ujjain",
    // hero
    "hero.eyebrow": "Blessed at Mahakaleshwar",
    "hero.h1a": "Sacred Prasad",
    "hero.h1b": "from the Holy City",
    "hero.h1c": "of Ujjain",
    "hero.sub": "Handpicked, hygienically packed and devotedly offered at Shri Mahakaleshwar Jyotirlinga — delivered to your doorstep with devotion.",
    "hero.exploreCta": "Explore Prasad",
    "hero.storyCta": "Our Story",
    "hero.devotees": "10,000+ Happy Devotees",
    "hero.rating": "4.9 avg rating",
    "hero.bestseller": "Bestseller",
    "hero.priceFrom": "From ₹299 · Free shipping",
    // welcome
    "welcome.title": "Welcome to Mahankal Prasad",
    "welcome.body": "Bringing you the divine essence of Ujjain — home to Lord Mahakal, one of the twelve sacred Jyotirlingas. Every offering is prepared with purity, sanctified through rituals and delivered with the blessings of Bhagwan Mahakaleshwar.",
    // featured
    "featured.eyebrow": "Curated Offerings",
    "featured.title": "Featured Prasad",
    "featured.viewAll": "View all →",
    // why
    "why.eyebrow": "Why Choose Us",
    "why.title": "Rooted in Devotion, Delivered with Care",
    "why.blessed.t": "Devotedly Offered at Mahakal",
    "why.blessed.b": "Every product is offered at the sacred Mahakaleshwar Jyotirlinga in Ujjain.",
    "why.pure.t": "Pure & Authentic",
    "why.pure.b": "Prepared with premium ingredients following traditional Vedic guidelines.",
    "why.deliver.t": "Pan-India Delivery",
    "why.deliver.b": "Fast, hygienic delivery across every corner of India in 3–7 days.",
    "why.secure.t": "Secure & Trusted",
    "why.secure.b": "10,000+ happy devotees, safe payments and hassle-free returns.",
    // ordering
    "order.eyebrow": "Easy Ordering",
    "order.title": "Prasad in 3 Simple Steps",
    "order.s1.t": "Choose your Prasad",
    "order.s1.b": "Browse curated offerings and select what your heart calls for.",
    "order.s2.t": "Secure Checkout",
    "order.s2.b": "Pay via UPI, cards, net banking or Cash on Delivery.",
    "order.s3.t": "Delivered to Your Door",
    "order.s3.b": "Blessed prasad arrives with love and devotion across India.",
    // reviews
    "rev.eyebrow": "Voices of Devotion",
    "rev.title": "Loved by 10,000+ Devotees",
    // cta
    "cta.title": "Begin Your Divine Journey",
    "cta.sub": "Bring the blessings of Mahakal home. Order authentic prasad today.",
    "cta.btn": "Shop Now",
    // shop
    "shop.eyebrow": "Our Collection",
    "shop.title": "Sacred Prasad & Puja",
    "shop.sub": "Devotedly offered at Mahakaleshwar Jyotirlinga, Ujjain",
    "shop.searchPh": "Search prasad, puja kits, mala…",
    "shop.all": "All",
    "shop.empty": "No products found. Try a different search.",
    "shop.loading": "Loading blessings…",
    // cart
    "cart.title": "Your Sacred Cart",
    "cart.empty": "Your cart is empty.",
    "cart.summary": "Order Summary",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping",
    "cart.tax": "Tax (est.)",
    "cart.free": "FREE",
    "cart.total": "Total",
    "cart.checkout": "Proceed to Checkout",
    "cart.remove": "Remove",
    "cart.browse": "Browse Prasad",
    "cart.loginRequired": "Please login to view your cart",
    // footer
    "foot.fast.t": "Fast Delivery",
    "foot.fast.b": "Across India, 3-7 days",
    "foot.secure.t": "Secure Payments",
    "foot.secure.b": "100% Protected",
    "foot.authentic.t": "Blessed & Authentic",
    "foot.authentic.b": "Direct from Ujjain",
    "foot.returns.t": "Easy Returns",
    "foot.returns.b": "7-day return policy",
    "foot.about": "Devotedly offered prasad and puja items from Mahakaleshwar Jyotirlinga, delivered to your doorstep with devotion.",
    "foot.disclaimer": "Note: This service is not affiliated with the temple management.",
    "foot.shop": "Shop",
    "foot.allProducts": "All Products",
    "foot.prasad": "Prasad",
    "foot.puja": "Puja Items",
    "foot.spiritual": "Spiritual",
    "foot.info": "Information",
    "foot.aboutUs": "About Us",
    "foot.contactUs": "Contact Us",
    "foot.shipping": "Shipping & Returns",
    "foot.privacy": "Privacy Policy",
    "foot.terms": "Terms & Conditions",
    "foot.getInTouch": "Get in Touch",
    "foot.newsletter": "Newsletter",
    "foot.subscribe": "Subscribe",
    "foot.emailPh": "your@email.com",
    "foot.copyright": "CHOUHAN AND SONS ENTERPRISES · Mahankal Prasad · All rights reserved",
    "foot.secured": "Secured Payments",
    // lang
    "lang.toggle": "हिन्दी",
  },
  hi: {
    "top.freeShip": "₹499 से ऊपर के ऑर्डर पर पूरे भारत में मुफ्त शिपिंग",
    "top.offered": "श्री महाकालेश्वर ज्योतिर्लिंग में श्रद्धापूर्वक अर्पित",
    "top.disclaimer": "यह सेवा मंदिर प्रबंधन से संबद्ध नहीं है",
    "nav.home": "होम",
    "nav.shop": "दुकान",
    "nav.about": "हमारे बारे में",
    "nav.contact": "संपर्क",
    "nav.faqs": "प्रश्नोत्तर",
    "nav.login": "लॉगिन",
    "nav.logout": "लॉगआउट",
    "nav.myOrders": "मेरे ऑर्डर",
    "nav.wishlist": "पसंदीदा",
    "nav.searchPh": "प्रसाद, पूजा किट खोजें…",
    "nav.tagline": "उज्जैन से पवित्र",
    "hero.eyebrow": "महाकालेश्वर में अर्पित",
    "hero.h1a": "पवित्र प्रसाद",
    "hero.h1b": "पावन नगरी उज्जैन",
    "hero.h1c": "से आपके द्वार",
    "hero.sub": "हस्तचयनित, स्वच्छता से पैक और श्री महाकालेश्वर ज्योतिर्लिंग में श्रद्धापूर्वक अर्पित — भक्ति के साथ आपके द्वार तक पहुँचाया गया।",
    "hero.exploreCta": "प्रसाद देखें",
    "hero.storyCta": "हमारी कहानी",
    "hero.devotees": "10,000+ प्रसन्न भक्त",
    "hero.rating": "4.9 औसत रेटिंग",
    "hero.bestseller": "सर्वाधिक बिकने वाला",
    "hero.priceFrom": "₹299 से · मुफ्त शिपिंग",
    "welcome.title": "महांकाल प्रसाद में आपका स्वागत है",
    "welcome.body": "उज्जैन की दिव्य आभा आपके घर तक — भगवान महाकाल का पावन धाम, बारह ज्योतिर्लिंगों में से एक। प्रत्येक अर्पण शुद्धता से तैयार, विधिवत संस्कारित और भगवान महाकालेश्वर के आशीर्वाद के साथ भेजा जाता है।",
    "featured.eyebrow": "विशेष अर्पण",
    "featured.title": "फीचर्ड प्रसाद",
    "featured.viewAll": "सब देखें →",
    "why.eyebrow": "हमें क्यों चुनें",
    "why.title": "भक्ति में निहित, सेवा में समर्पित",
    "why.blessed.t": "महाकाल में अर्पित",
    "why.blessed.b": "प्रत्येक उत्पाद उज्जैन के पावन महाकालेश्वर ज्योतिर्लिंग में श्रद्धापूर्वक अर्पित है।",
    "why.pure.t": "शुद्ध व प्रामाणिक",
    "why.pure.b": "पारंपरिक वैदिक विधि से चुनिंदा सामग्री से निर्मित।",
    "why.deliver.t": "पूरे भारत में डिलीवरी",
    "why.deliver.b": "3–7 दिनों में तेज़ व स्वच्छ डिलीवरी, भारत के हर कोने में।",
    "why.secure.t": "सुरक्षित व विश्वसनीय",
    "why.secure.b": "10,000+ प्रसन्न भक्त, सुरक्षित भुगतान और आसान रिटर्न।",
    "order.eyebrow": "आसान ऑर्डरिंग",
    "order.title": "3 सरल चरणों में प्रसाद",
    "order.s1.t": "अपना प्रसाद चुनें",
    "order.s1.b": "चुनिंदा अर्पणों में से जो मन को भाए वह चुनें।",
    "order.s2.t": "सुरक्षित चेकआउट",
    "order.s2.b": "UPI, कार्ड, नेट बैंकिंग या कैश ऑन डिलीवरी।",
    "order.s3.t": "आपके द्वार तक",
    "order.s3.b": "आशीर्वादित प्रसाद भारत भर में प्रेम और भक्ति के साथ।",
    "rev.eyebrow": "भक्तों की वाणी",
    "rev.title": "10,000+ भक्तों का विश्वास",
    "cta.title": "अपनी दिव्य यात्रा प्रारंभ करें",
    "cta.sub": "महाकाल का आशीर्वाद घर लाइए। आज ही असली प्रसाद ऑर्डर करें।",
    "cta.btn": "अभी खरीदें",
    "shop.eyebrow": "हमारा संग्रह",
    "shop.title": "पवित्र प्रसाद व पूजा",
    "shop.sub": "श्री महाकालेश्वर ज्योतिर्लिंग, उज्जैन में श्रद्धापूर्वक अर्पित",
    "shop.searchPh": "प्रसाद, पूजा किट, माला खोजें…",
    "shop.all": "सभी",
    "shop.empty": "कोई उत्पाद नहीं मिला। कृपया कुछ और खोजें।",
    "shop.loading": "आशीर्वाद लोड हो रहा है…",
    "cart.title": "आपकी पवित्र कार्ट",
    "cart.empty": "आपकी कार्ट खाली है।",
    "cart.summary": "ऑर्डर सारांश",
    "cart.subtotal": "उप-कुल",
    "cart.shipping": "शिपिंग",
    "cart.tax": "कर (अनुमानित)",
    "cart.free": "मुफ्त",
    "cart.total": "कुल",
    "cart.checkout": "चेकआउट पर जाएँ",
    "cart.remove": "हटाएँ",
    "cart.browse": "प्रसाद देखें",
    "cart.loginRequired": "कार्ट देखने के लिए कृपया लॉगिन करें",
    "foot.fast.t": "तेज़ डिलीवरी",
    "foot.fast.b": "पूरे भारत में, 3-7 दिन",
    "foot.secure.t": "सुरक्षित भुगतान",
    "foot.secure.b": "100% सुरक्षित",
    "foot.authentic.t": "आशीर्वादित व प्रामाणिक",
    "foot.authentic.b": "उज्जैन से सीधे",
    "foot.returns.t": "आसान रिटर्न",
    "foot.returns.b": "7-दिन की रिटर्न नीति",
    "foot.about": "श्री महाकालेश्वर ज्योतिर्लिंग में श्रद्धापूर्वक अर्पित प्रसाद एवं पूजा सामग्री, भक्ति के साथ आपके द्वार तक।",
    "foot.disclaimer": "नोट: यह सेवा मंदिर प्रबंधन से संबद्ध नहीं है।",
    "foot.shop": "दुकान",
    "foot.allProducts": "सभी उत्पाद",
    "foot.prasad": "प्रसाद",
    "foot.puja": "पूजा सामग्री",
    "foot.spiritual": "आध्यात्मिक",
    "foot.info": "जानकारी",
    "foot.aboutUs": "हमारे बारे में",
    "foot.contactUs": "संपर्क करें",
    "foot.shipping": "शिपिंग व रिटर्न",
    "foot.privacy": "गोपनीयता नीति",
    "foot.terms": "नियम व शर्तें",
    "foot.getInTouch": "संपर्क में रहें",
    "foot.newsletter": "न्यूज़लेटर",
    "foot.subscribe": "सब्सक्राइब",
    "foot.emailPh": "आपका@ईमेल.com",
    "foot.copyright": "CHOUHAN AND SONS ENTERPRISES · महांकाल प्रसाद · सर्वाधिकार सुरक्षित",
    "foot.secured": "सुरक्षित भुगतान",
    "lang.toggle": "English",
  },
};

const LangCtx = createContext(null);
export const useLang = () => useContext(LangCtx);

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => localStorage.getItem("mp_lang") || "en");

  useEffect(() => {
    localStorage.setItem("mp_lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = (l) => setLangState(l);
  const toggle = () => setLangState((l) => (l === "en" ? "hi" : "en"));
  const t = (key) => (dict[lang] && dict[lang][key]) || dict.en[key] || key;

  return <LangCtx.Provider value={{ lang, setLang, toggle, t }}>{children}</LangCtx.Provider>;
};
